.TH NESDUMP2FF 1 nesdump2ff
.SH NAME
nesdump2ff - Dumps the character rom of a .nes file to a farbfeld file.
.SH SYNOPSIS
nesdump2ff [FILE]
.SH DESCRIPTION
Dumps the character rom of a .nes file to a farbfeld file in standard output.
.P
Example: nesdump2ff file.nes > file.ff
.SH AUTHOR
Written by Gabriel Martins
.SH COPYRIGHT
.P
Copyright (C) Gabriel Martins 2020. License GPLv3+: GNU GPL Version 3 or later. This is free software. You are free to change and redistribute it.   
There is NO WARRANTY, to the extent permited by law.   
